source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'quiet_assets'
gem 'jquery-rails'
gem 'turbolinks'
gem 'capistrano', '~> 3.2.0'
gem 'capistrano-rbenv', github: "capistrano/rbenv"
gem 'capistrano-bundler', '~> 1.1.2'
gem 'capistrano-rails', '~> 1.1.1'
gem 'byebug'
gem 'puma'
gem 'bcrypt-ruby', '3.1.2'
gem 'annotate', "~> 2.6.5"
gem 'bootstrap-sass', '~> 3.2.0'
gem 'faker'
gem 'acts_as_votable', '~> 0.10.0'
gem 'will_paginate', '~> 3.0'
gem 'twitter-typeahead-rails'
gem 'rails_12factor'
